config/routes.rb
Rails.application.routes.draw do
  resources :games
  resources :tags
  resources :things
  resources :players
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/thing.rb
class Thing < ApplicationRecord
	has_many :tags, through: :thing_tags
	has_many :thing_tags, dependent: :destroy
	has_many :games, through: :game_things
	has_many :game_things, dependent: :destroy
	has_many :players, through: :game_players
	has_many :game_players, dependent: :destroy
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  before_action :set_thing, only: %i[ show edit update destroy ]

  # GET /things or /things.json
  def index
    @things = Thing.all
  end

  # GET /things/1 or /things/1.json
  def show
  end

  # GET /things/new
  def new
    @thing = Thing.new
  end

  # GET /things/1/edit
  def edit
  end

  # POST /things or /things.json
  def create
    @thing = Thing.new(thing_params)

    respond_to do |format|
      if @thing.save
        format.html { redirect_to thing_url(@thing), notice: "Thing was successfully created." }
        format.json { render :show, status: :created, location: @thing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /things/1 or /things/1.json
  def update
    respond_to do |format|
      if @thing.update(thing_params)
        format.html { redirect_to thing_url(@thing), notice: "Thing was successfully updated." }
        format.json { render :show, status: :ok, location: @thing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /things/1 or /things/1.json
  def destroy
    @thing.destroy

    respond_to do |format|
      format.html { redirect_to things_url, notice: "Thing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thing
      @thing = Thing.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def thing_params
      params.require(:thing).permit(:name, :link, :img)
    end
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/views/things/_form.html.erb
<%= form_with(model: thing) do |form| %>
  <% if thing.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(thing.errors.count, "error") %> prohibited this thing from being saved:</h2>

      <ul>
        <% thing.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :link, style: "display: block" %>
    <%= form.text_field :link %>
  </div>

  <div>
    <%= form.label :img, style: "display: block" %>
    <%= form.text_field :img %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/things/_thing.html.erb
<div id="<%= dom_id thing %>">
  <p>
    <strong>Name:</strong>
    <%= thing.name %>
  </p>

  <p>
    <strong>Link:</strong>
    <%= thing.link %>
  </p>

  <p>
    <strong>Img:</strong>
    <%= thing.img %>
  </p>

</div>

app/views/things/edit.html.erb
<h1>Editing thing</h1>

<%= render "form", thing: @thing %>

<br>

<div>
  <%= link_to "Show this thing", @thing %> |
  <%= link_to "Back to things", things_path %>
</div>

app/views/things/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Things</h1>

<div id="things">
  <% @things.each do |thing| %>
    <%= render thing %>
    <p>
      <%= link_to "Show this thing", thing %>
    </p>
  <% end %>
</div>

<%= link_to "New thing", new_thing_path %>

app/views/things/new.html.erb
<h1>New thing</h1>

<%= render "form", thing: @thing %>

<br>

<div>
  <%= link_to "Back to things", things_path %>
</div>

app/views/things/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @thing %>

<div>
  <%= link_to "Edit this thing", edit_thing_path(@thing) %> |
  <%= link_to "Back to things", things_path %>

  <%= button_to "Destroy this thing", @thing, method: :delete %>
</div>